language: java

before_install:
 - chmod +x gradlew

jdk:
  - oraclejdk8

test:
  post:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)